name: Verifying code with Black and Flake8

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python Version
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Link with black
        run: |
          pip install black
          black .
        continue-on-error: true
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .
        continue-on-error: true
